[workspace]
members = [
    "chapter-1-introduction/hello-cargo",
    "chapter-2-programming-a-guessing-game/guessing-game",
    "chapter-3-common-programming-concepts/functions",
    "chapter-3-common-programming-concepts/variables",
    "chapter-4-understanding-ownership/ownership",
    "chapter-5-using-structs/structs",
    "chapter-6-enums-and-pattern-matching/enums",
    "chapter-7-packages-crates-modules/backyard",
    "chapter-7-packages-crates-modules/resturant",
    "chapter-8-common-collections/collections",
    "chapter-9-error-handling/errors",
]
resolver = "3"
